on: push
name: deploy
jobs:
  deploy:
    name: Deploy send consumer
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: build and push to docker
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          respository: raymelguerra/send-consumer
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}